using UnityEngine;

namespace LastGround.Data.Crowd
{
    /// <summary>
    /// One crowd body baked for GPU animation (TDD_02 §21.3, D-018): LOD meshes whose vertices carry bone indices
    /// (UV1) and weights (UV2), and a bone-matrix texture (3 texels per bone per frame, RGBAHalf) shared by all LODs.
    /// Generated by the editor CrowdBaker; do not edit by hand.
    /// </summary>
    [CreateAssetMenu(menuName = "LastGround/Crowd/Animation Set")]
    public sealed class CrowdAnimationSet : ScriptableObject
    {
        public string Id;
        public Mesh[] Lods;
        public Texture2D BoneTexture;
        public int BoneCount;
        public int TotalFrames;
        public float FrameRate = 30f;
        public CrowdClip[] Clips;

        /// <summary>Bind-pose height in metres after normalisation.</summary>
        public float Height;

        /// <summary>Returns the clip for an id, falling back to Walk, then the first clip.</summary>
        public CrowdClip GetClip(CrowdClipId id)
        {
            CrowdClip fallback = Clips[0];
            for (int i = 0; i < Clips.Length; i++)
            {
                if (Clips[i].Id == id) return Clips[i];
                if (Clips[i].Id == CrowdClipId.Walk) fallback = Clips[i];
            }
            return fallback;
        }
    }
}
