using System;
using UnityEngine;

namespace LastGround.Data.Map
{
    /// <summary>Environmental interactables placed on a map (TDD_01 §12.3). Wire byte: append only.</summary>
    public enum InteractableKind : byte
    {
        ExplosiveBarrel = 0,
        FuelTank = 1,
        AmmoCrate = 2,
        MedStation = 3,
    }

    /// <summary>What an event anchor is for (TDD_01 §11.3, §12).</summary>
    public enum MapAnchorKind : byte
    {
        SupplyDrop = 0,
        WeaponCache = 1,
        Generator = 2,
        RescueSignal = 3,
        Extraction = 4,
        LootChest = 5,
    }

    /// <summary>
    /// One playable map (TDD_01 §11.3): world size, regions, baked nav grid, lamps (lighting grid pools), player spawn
    /// points, event anchors, region portals and the prerendered mini-map. Generated by the editor map builder;
    /// read-only at runtime.
    /// </summary>
    [CreateAssetMenu(menuName = "LastGround/Map/Map")]
    public sealed class MapDefinition : ScriptableObject
    {
        [Serializable]
        public struct Lamp
        {
            public Vector2 Position;
            public float Radius;
            public Color Color;
        }

        [Serializable]
        public struct Anchor
        {
            public string Id;
            public MapAnchorKind Kind;
            /// <summary>Index into <see cref="Regions"/>.</summary>
            public int Region;
            public Vector2 Position;
        }

        /// <summary>A walkable connection between two regions (portal graph, TDD_01 §11.2).</summary>
        [Serializable]
        public struct Portal
        {
            public int RegionA;
            public int RegionB;
            public Vector2 Position;
        }

        /// <summary>A placed interactable; its index in <see cref="Interactables"/> is its stable network id.</summary>
        [Serializable]
        public struct Interactable
        {
            public InteractableKind Kind;
            public Vector2 Position;
            public float Yaw;
        }

        public string Id = "industrial";
        public string NameKey = "map.industrial";
        /// <summary>Square world size in metres, centred on the origin.</summary>
        public float Size = 200f;
        public NavGridAsset NavGrid;
        public MapZoneSet Regions;
        public Lamp[] Lamps;
        public Vector2[] PlayerSpawns;
        public Anchor[] Anchors;
        public Portal[] Portals;
        public Interactable[] Interactables;

        [Header("Mini-map (TDD_01 §11.5: orthographic prerender)")]
        public Texture2D Minimap;
        /// <summary>World XZ rectangle the mini-map covers.</summary>
        public Rect MinimapRect;

        /// <summary>Region index containing the point, or -1.</summary>
        public int RegionAt(float x, float z)
        {
            if (Regions == null) return -1;
            for (int i = 0; i < Regions.Zones.Length; i++) if (Regions.Zones[i].Contains(x, z)) return i;
            return -1;
        }
    }
}
