using UnityEngine;

namespace LastGround.Data.Map
{
    /// <summary>
    /// Baked walkability grid for zombie navigation (TDD_01 §8.3): 1 = walkable, 0 = blocked, row-major (z * width + x).
    /// Generated by the editor NavGridBaker from Environment colliders; read-only at runtime.
    /// </summary>
    [CreateAssetMenu(menuName = "LastGround/Map/Nav Grid")]
    public sealed class NavGridAsset : ScriptableObject
    {
        public int Width;
        public int Height;
        public float CellSize = 1f;

        /// <summary>World XZ of cell (0,0)'s lower-left corner.</summary>
        public Vector2 Origin;

        public byte[] Cells;
    }
}
